trivy-scan-images:
  stage: security-scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - echo "scan images"
    - trivy image --severity HIGH,CRITICAL python:3.11-slim --exit-code 0
    - trivy image --severity HIGH,CRITICAL rabbitmq:3.12-management --exit-code 0
    - echo "scan termine"
  only:
    - main
    - master
  tags:
    - SAK5